using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class Materialappd
    {
        public int Autoid { get; set; }
        public int Id { get; set; }
        public string Cinvcode { get; set; }
        public decimal? Inum { get; set; }
        public decimal? Iquantity { get; set; }
        public string Cbatch { get; set; }
        public decimal? Iinvexchrate { get; set; }
        public string Cfree1 { get; set; }
        public string Cfree2 { get; set; }
        public DateTime? Dduedate { get; set; }
        public string Cbcloser { get; set; }
        public decimal? Foutquantity { get; set; }
        public decimal? Foutnum { get; set; }
        public DateTime? Dvdate { get; set; }
        public string Cdefine22 { get; set; }
        public string Cdefine23 { get; set; }
        public string Cdefine24 { get; set; }
        public string Cdefine25 { get; set; }
        public double? Cdefine26 { get; set; }
        public double? Cdefine27 { get; set; }
        public string CitemClass { get; set; }
        public string Citemcode { get; set; }
        public string Cname { get; set; }
        public string Citemcname { get; set; }
        public string Cfree3 { get; set; }
        public string Cfree4 { get; set; }
        public string Cfree5 { get; set; }
        public string Cfree6 { get; set; }
        public string Cfree7 { get; set; }
        public string Cfree8 { get; set; }
        public string Cfree9 { get; set; }
        public string Cfree10 { get; set; }
        public DateTime? Dmadedate { get; set; }
        public int? Imassdate { get; set; }
        public string Cdefine28 { get; set; }
        public string Cdefine29 { get; set; }
        public string Cdefine30 { get; set; }
        public string Cdefine31 { get; set; }
        public string Cdefine32 { get; set; }
        public string Cdefine33 { get; set; }
        public int? Cdefine34 { get; set; }
        public int? Cdefine35 { get; set; }
        public DateTime? Cdefine36 { get; set; }
        public DateTime? Cdefine37 { get; set; }
        public string Cwhcode { get; set; }
        public string Cinvaddcode { get; set; }
        public byte? Igrouptype { get; set; }
        public string Cinvname { get; set; }
        public string Cinvstd { get; set; }
        public string Creplaceitem { get; set; }
        public string Cinvdefine1 { get; set; }
        public string Cinvdefine2 { get; set; }
        public string Cinvdefine3 { get; set; }
        public int? Iid { get; set; }
        public string Cinvdefine4 { get; set; }
        public string Cinvdefine5 { get; set; }
        public string Cinvdefine6 { get; set; }
        public string Cinvdefine7 { get; set; }
        public string Cinvdefine8 { get; set; }
        public string Cinvdefine9 { get; set; }
        public string Cinvdefine10 { get; set; }
        public int? Cinvdefine11 { get; set; }
        public int? Cinvdefine12 { get; set; }
        public double? Cinvdefine13 { get; set; }
        public double? Cinvdefine14 { get; set; }
        public DateTime? Cinvdefine15 { get; set; }
        public DateTime? Cinvdefine16 { get; set; }
        public string Cwhname { get; set; }
        public string Cassunit { get; set; }
        public string CinvaUnit { get; set; }
        public string Cinvccode { get; set; }
        public string Cmassunit { get; set; }
        public string  Cinvm_Unit { get; set; }
        public string Corufts { get; set; }
        public short? Iexpiratdatecalcu { get; set; }
        public string Cexpirationdate { get; set; }
        public DateTime? Dexpirationdate { get; set; }
        public decimal? Cbatchproperty1 { get; set; }
        public decimal? Cbatchproperty2 { get; set; }
        public decimal? Cbatchproperty3 { get; set; }
        public decimal? Cbatchproperty4 { get; set; }
        public decimal? Cbatchproperty5 { get; set; }
        public string Cbatchproperty6 { get; set; }
        public string Cbatchproperty7 { get; set; }
        public string Cbatchproperty8 { get; set; }
        public string Cbatchproperty9 { get; set; }
        public DateTime? Cbatchproperty10 { get; set; }
        public string Cbmemo { get; set; }
        public int? Irowno { get; set; }
        public long? Impoids { get; set; }
        public string Cmworkcentercode { get; set; }
        public string Cmworkcenter { get; set; }
        public string Cmocode { get; set; }
        public int? Imoseq { get; set; }
        public string Cmolotcode { get; set; }
        public string Iopseq { get; set; }
        public string Copdesc { get; set; }
        public string Invcode { get; set; }
        public string Invname { get; set; }
        public string Invstd { get; set; }
        public string Isodid { get; set; }
        public byte Isotype { get; set; }
        public string Csocode { get; set; }
        public int? Isoseq { get; set; }
        public string Cdemandmemo { get; set; }
        public byte? Iordertype { get; set; }
        public int? Iorderdid { get; set; }
        public string Iordercode { get; set; }
        public int? Iorderseq { get; set; }
        public string Cservicecode { get; set; }
        public string Cciqbookcode { get; set; }
        public int? Iomomid { get; set; }
        public int? Iomodid { get; set; }
        public string Comcode { get; set; }
        public string Crejectcode { get; set; }
        public string Ipesodid { get; set; }
        public byte? Ipesotype { get; set; }
        public string Cpesocode { get; set; }
        public int? Ipesoseq { get; set; }
        public string Cbsysbarcode { get; set; }
        public decimal? Ipickedquantity { get; set; }
        public decimal? Ipickednum { get; set; }
        public string Csourcemocode { get; set; }
        public int? Isourcemodetailsid { get; set; }
        public string Cplanlotcode { get; set; }
        public decimal? Iavaquantity { get; set; }
        public decimal? Iavanum { get; set; }
        public decimal? Ipresent { get; set; }
        public decimal? Ipresentnum { get; set; }
        public string Cfactorycode { get; set; }
        public string Cfactoryname { get; set; }
    }
}
