using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class OmMomaterialshead
    {
        public int Moid { get; set; }
        public int Modetailsid { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvname { get; set; }
        public string Cinvstd { get; set; }
        public string Cinvaddcode { get; set; }
        public decimal? Iquotedprice { get; set; }
        public decimal? Iquantity { get; set; }
        public decimal? Inum { get; set; }
        public decimal? Iunitprice { get; set; }
        public decimal? Imoney { get; set; }
        public decimal? Itax { get; set; }
        public decimal? Isum { get; set; }
        public decimal? Idiscount { get; set; }
        public decimal? Inatunitprice { get; set; }
        public decimal? Inatmoney { get; set; }
        public decimal? Inattax { get; set; }
        public decimal? Inatsum { get; set; }
        public decimal? Inatdiscount { get; set; }
        public DateTime? Darrivedate { get; set; }
        public string Cfree2 { get; set; }
        public string Cfree1 { get; set; }
        public string Cunitid { get; set; }
        public string Ccomunitcode { get; set; }
        public string CinvmUnit { get; set; }
        public byte? Igrouptype { get; set; }
        public string Cgroupcode { get; set; }
        public string CinvaUnit { get; set; }
        public decimal? Iinvexchrate { get; set; }
        public string Cinvdefine1 { get; set; }
        public string Cinvdefine2 { get; set; }
        public string Cinvdefine3 { get; set; }
        public string Cinvdefine4 { get; set; }
        public string Cinvdefine5 { get; set; }
        public string Cinvdefine6 { get; set; }
        public string Cinvdefine7 { get; set; }
        public string Cinvdefine8 { get; set; }
        public string Cinvdefine9 { get; set; }
        public string Cinvdefine10 { get; set; }
        public int? Cinvdefine11 { get; set; }
        public int? Cinvdefine12 { get; set; }
        public double? Cinvdefine13 { get; set; }
        public double? Cinvdefine14 { get; set; }
        public DateTime? Cinvdefine15 { get; set; }
        public DateTime? Cinvdefine16 { get; set; }
        public string Cdefine22 { get; set; }
        public string Cdefine23 { get; set; }
        public string Cdefine24 { get; set; }
        public string Cdefine25 { get; set; }
        public double? Cdefine26 { get; set; }
        public double? Cdefine27 { get; set; }
        public string Cdefine28 { get; set; }
        public string Cdefine29 { get; set; }
        public string Cdefine30 { get; set; }
        public string Cdefine31 { get; set; }
        public string Cdefine32 { get; set; }
        public string Cdefine33 { get; set; }
        public int? Cdefine34 { get; set; }
        public int? Cdefine35 { get; set; }
        public DateTime? Cdefine36 { get; set; }
        public DateTime? Cdefine37 { get; set; }
        public decimal? Ipertaxrate { get; set; }
        public string Citemcode { get; set; }
        public string Citemname { get; set; }
        public string CitemClass { get; set; }
        public string CitemName1 { get; set; }
        public string Cfree3 { get; set; }
        public string Cfree4 { get; set; }
        public string Cfree5 { get; set; }
        public string Cfree6 { get; set; }
        public string Cfree7 { get; set; }
        public string Cfree8 { get; set; }
        public string Cfree9 { get; set; }
        public string Cfree10 { get; set; }
        public decimal? Itaxprice { get; set; }
        public int? Iinvauthid { get; set; }
        public bool? Btaxcost { get; set; }
        public decimal? Iarrqty { get; set; }
        public int? Cinvauthid { get; set; }
        public decimal? Iinvqty { get; set; }
        public decimal? Ioritotal { get; set; }
        public byte Bgsp { get; set; }
        public string Csource { get; set; }
        public decimal? Iinvmoney { get; set; }
        public string Cbcloser { get; set; }
        public byte Bomtype { get; set; }
        public int? Version { get; set; }
        public string Versiondesc { get; set; }
        public string Identcode { get; set; }
        public string Identdesc { get; set; }
        public DateTime? Versioneffdate { get; set; }
        public DateTime? Versionenddate { get; set; }
        public string Cveninvcode { get; set; }
        public string Cveninvname { get; set; }
        public DateTime? Dstartdate { get; set; }
        public decimal? Ireceivedqty { get; set; }
        public decimal Ireceivednum { get; set; }
        public decimal? Ireceivedmoney { get; set; }
        public decimal? Iinvnum { get; set; }
        public decimal? Inatinvmoney { get; set; }
        public decimal? Itotal { get; set; }
        public decimal? Iarrnum { get; set; }
        public decimal? Iarrmoney { get; set; }
        public decimal? Inatarrmoney { get; set; }
        public string Sodid { get; set; }
        public int? Bomid { get; set; }
        public int Mrpdetailsid { get; set; }
        public decimal? Fparentscrp { get; set; }
        public decimal? Imaterialsendqty { get; set; }
        public string Corufts { get; set; }
        public string Imainid { get; set; }
        public int? Irowno { get; set; }
        public byte Sotype { get; set; }
        public string Csocode { get; set; }
        public int? Ivtids { get; set; }
        public string Cupsocode { get; set; }
        public int? Cupsoids { get; set; }
        public int? Isosid { get; set; }
        public string Cdemandcode { get; set; }
        public string Cdetailsdemandmemo { get; set; }
        public string Cdemandmemo { get; set; }
        public DateTime? Dbclosedate { get; set; }
        public DateTime? Dbclosetime { get; set; }
        public string Csrpolicy { get; set; }
        public short? Irequiretrackstyle { get; set; }
        public int? Ivouchrowno { get; set; }
        public short? Iexpiratdatecalcu { get; set; }
        public short? Cmassunit { get; set; }
        public short? Imassdate { get; set; }
        public string Cbmemo { get; set; }
        public int? Icusbomid { get; set; }
        public string Cbsysbarcode { get; set; }
        public string Icopyid { get; set; }
        public byte Iproducttype { get; set; }
        public int? Imainmodetailsid { get; set; }
        public string Cmaininvcode { get; set; }
        public int? Imainmomaterialsid { get; set; }
        public decimal? Imrpqty { get; set; }
        public decimal? Freworkquantity { get; set; }
        public decimal? Freworknum { get; set; }
        public string Isourcemocode { get; set; }
        public int? Isourcemodetailsid { get; set; }
        public byte Isoordertype { get; set; }
        public int? Iorderdid { get; set; }
        public string Csoordercode { get; set; }
        public int? Iorderseq { get; set; }
        public string Cplanlotnumber { get; set; }
        public string Cplanmethod { get; set; }
        public string Cfactorycode { get; set; }
        public string Cfactoryname { get; set; }
        public string Ufts { get; set; }
        public string Ccode { get; set; }
        public DateTime? Ddate { get; set; }
        public string Ccloser { get; set; }
        public string Cverifier { get; set; }
        public string Cmaker { get; set; }
        public byte? Cstate { get; set; }
        public string CinvaddcodeT { get; set; }
        public string CinvstdT { get; set; }
        public DateTime? Dverifydate { get; set; }
        public string Cvencode { get; set; }
        public string Cvenabbname { get; set; }
        public int? Iswfcontrolled { get; set; }
        public int? Iverifystatenew { get; set; }
        public string Cchangeverifier { get; set; }
        public string Cchanger { get; set; }
        public string Clocker { get; set; }
        public byte Iordertype { get; set; }
        public byte Brework { get; set; }
    }
}
