using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class PuArrBody
    {
        public int? Id { get; set; }
        public string Cwhcode { get; set; }
        public string Cwhname { get; set; }
        public int Autoid { get; set; }
        public string Cinvcode { get; set; }
        public string Cinvaddcode { get; set; }
        public string Cinvname { get; set; }
        public string Cinvstd { get; set; }
        public string Cinvccode { get; set; }
        public string Cunitid { get; set; }
        public string Ccomunitcode { get; set; }
        public string Cinvm_Unit { get; set; }
        public byte? Igrouptype { get; set; }
        public string Cgroupcode { get; set; }
        public string Cinva_Unit { get; set; }
        public bool? Bservice { get; set; }
        public decimal? Iinvexchrate { get; set; }
        public bool? Binvbatch { get; set; }
        public string Cbatch { get; set; }
        public DateTime? Dvdate { get; set; }
        public DateTime? Dpdate { get; set; }
        public int? Imassdate { get; set; }
        public byte? Cmassunit { get; set; }
        public string Cgspstate { get; set; }
        public string Ccloser { get; set; }
        public decimal? Ioritaxcost { get; set; }
        public int? Icorid { get; set; }
        public decimal Iquantity { get; set; }
        public decimal? Inum { get; set; }
        public decimal? Ioricost { get; set; }
        public decimal? Iorimoney { get; set; }
        public decimal? Ioritaxprice { get; set; }
        public decimal? Iorisum { get; set; }
        public decimal? Icost { get; set; }
        public decimal? Imoney { get; set; }
        public decimal? Itaxprice { get; set; }
        public decimal? Isum { get; set; }
        public string Cbcloser { get; set; }
        public string Cfree1 { get; set; }
        public string Cfree2 { get; set; }
        public string Cdefine22 { get; set; }
        public string Cdefine23 { get; set; }
        public string Cdefine24 { get; set; }
        public string Cdefine25 { get; set; }
        public double? Cdefine26 { get; set; }
        public double? Cdefine27 { get; set; }
        public string Cdefine28 { get; set; }
        public string Cdefine29 { get; set; }
        public string Cdefine30 { get; set; }
        public string Cdefine31 { get; set; }
        public string Cdefine32 { get; set; }
        public string Cdefine33 { get; set; }
        public int? Cdefine34 { get; set; }
        public int? Cdefine35 { get; set; }
        public DateTime? Cdefine36 { get; set; }
        public DateTime? Cdefine37 { get; set; }
        public decimal Itaxrate { get; set; }
        public string Citemcode { get; set; }
        public string Citemname { get; set; }
        public string CitemClass { get; set; }
        public string CitemName1 { get; set; }
        public int? Iposid { get; set; }
        public decimal? Fvalidquantity { get; set; }
        public decimal? Fvalidnum { get; set; }
        public decimal? Fvalidinquan { get; set; }
        public decimal? Fvalidinnum { get; set; }
        public decimal? Fkpquantity { get; set; }
        public decimal? Finvalidquantity { get; set; }
        public decimal? Finvalidnum { get; set; }
        public decimal? Finvalidinquan { get; set; }
        public decimal? Fretquantity { get; set; }
        public decimal? Frefusequantity { get; set; }
        public decimal? Frefusenum { get; set; }
        public decimal? Frealquantity { get; set; }
        public decimal? Frealnum { get; set; }
        public string Cfree3 { get; set; }
        public string Cfree4 { get; set; }
        public string Cfree5 { get; set; }
        public string Cfree6 { get; set; }
        public string Cfree7 { get; set; }
        public string Cfree8 { get; set; }
        public string Cfree9 { get; set; }
        public string Cfree10 { get; set; }
        public string Cinvdefine1 { get; set; }
        public string Cinvdefine2 { get; set; }
        public string Cinvdefine3 { get; set; }
        public string Cinvdefine4 { get; set; }
        public string Cinvdefine5 { get; set; }
        public string Cinvdefine6 { get; set; }
        public string Cinvdefine7 { get; set; }
        public string Cinvdefine8 { get; set; }
        public string Cinvdefine9 { get; set; }
        public string Cinvdefine10 { get; set; }
        public int? Cinvdefine11 { get; set; }
        public int? Cinvdefine12 { get; set; }
        public double? Cinvdefine13 { get; set; }
        public double? Cinvdefine14 { get; set; }
        public DateTime? Cinvdefine15 { get; set; }
        public DateTime? Cinvdefine16 { get; set; }
        public bool? Rejectsource { get; set; }
        public byte Bgsp { get; set; }
        public int? Cinvauthid { get; set; }
        public bool? Btaxcost { get; set; }
        public byte Binspect { get; set; }
        public Guid? Contractrowguid { get; set; }
        public decimal? Iinvmpcost { get; set; }
        public int? Irowno { get; set; }
        public byte Sotype { get; set; }
        public string Csocode { get; set; }
        public string Cdemandmemo { get; set; }
        public byte Iordertype { get; set; }
        public string Csoordercode { get; set; }
        public int? Iorderseq { get; set; }
        public int? Iorderdid { get; set; }
        public int? Ippartid { get; set; }
        public decimal? Ipquantity { get; set; }
        public int? Iptoseq { get; set; }
        public string Cveninvcode { get; set; }
        public string Cveninvname { get; set; }
        public string Sodid { get; set; }
        public string Cordercode { get; set; }
        public byte Bexigency { get; set; }
        public string Contractcode { get; set; }
        public string Contractrowno { get; set; }
        public decimal? Fretnum { get; set; }
        public decimal? Fsumrefusequantity { get; set; }
        public decimal? Fsumrefusenum { get; set; }
        public decimal? Fdtquantity { get; set; }
        public decimal? Finvalidinnum { get; set; }
        public decimal? Finspectquantity { get; set; }
        public decimal? Finspectnum { get; set; }
        public int Vouchstate { get; set; }
        public decimal? Fininquantity { get; set; }
        public decimal? Fininnum { get; set; }
        public string DValidateDate { get; set; }
        public decimal? Inspecexchrate { get; set; }
        public int? Irejectautoid { get; set; }
        public short? Iexpiratdatecalcu { get; set; }
        public string Cexpirationdate { get; set; }
        public DateTime? Dexpirationdate { get; set; }
        public string Carrivalcode { get; set; }
        public decimal? Cbatchproperty1 { get; set; }
        public decimal? Cbatchproperty2 { get; set; }
        public decimal? Cbatchproperty3 { get; set; }
        public decimal? Cbatchproperty4 { get; set; }
        public decimal? Cbatchproperty5 { get; set; }
        public string Cbatchproperty6 { get; set; }
        public string Cbatchproperty7 { get; set; }
        public string Cbatchproperty8 { get; set; }
        public string Cbatchproperty9 { get; set; }
        public DateTime? Cbatchproperty10 { get; set; }
        public string Cupsocode { get; set; }
        public int? Ivouchrowno { get; set; }
        public string Cbmemo { get; set; }
        public string Cbsysbarcode { get; set; }
        public byte Iproducttype { get; set; }
        public string Cmaininvcode { get; set; }
        public int? Imainmodetailsid { get; set; }
        public string Isourcemocode { get; set; }
        public int? Isourcemodetailsid { get; set; }
        public decimal? Freworkquantity { get; set; }
        public decimal? Freworknum { get; set; }
        public decimal? Fsumreworkquantity { get; set; }
        public decimal? Fsumreworknum { get; set; }
        public string Planlotnumber { get; set; }
        public short? Bgift { get; set; }
        public DateTime? Dlineclosedate { get; set; }
        public string Cfactorycode { get; set; }
        public string Cfactoryname { get; set; }
    }
}
