using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class SADispatchlist
    {
        public string Ivouchstate { get; set; }
        public string CSysBarCode { get; set; }
        public bool? Bsaleoutcreatebill { get; set; }
        public string CCurrentAuditor { get; set; }
        public string Ufts { get; set; }
        public string CBusType { get; set; }
        public string CAccounter { get; set; }
        public int IVtid { get; set; }
        public string Outid { get; set; }
        public string CCreChpName { get; set; }
        public string CDlcode { get; set; }
        public string CVouchType { get; set; }
        public string Cvouchname { get; set; }
        public string CStcode { get; set; }
        public string CStname { get; set; }
        public string Ddate { get; set; }
        public string CDepCode { get; set; }
        public string CDepName { get; set; }
        public string CPersonCode { get; set; }
        public string CPersonName { get; set; }
        public string CSbvcode { get; set; }
        public string CSocode { get; set; }
        public DateTime? DDepEndDate { get; set; }
        public string CCusCode { get; set; }
        public string CCusAbbName { get; set; }
        public string CPayCode { get; set; }
        public string CSccode { get; set; }
        public string CScname { get; set; }
        public string CShipAddress { get; set; }
        public string CexchName { get; set; }
        public double IExchRate { get; set; }
        public double? ITaxRate { get; set; }
        public string CMemo { get; set; }
        public string CDefine1 { get; set; }
        public string CDefine2 { get; set; }
        public float? INetLock { get; set; }
        public int Breturnflag { get; set; }
        public string CPayName { get; set; }
        public string CCusOaddress { get; set; }
        public string CCusOtype { get; set; }
        public string CCusPayCond { get; set; }
        public int Dlid { get; set; }
        public string CVerifier { get; set; }
        public string CMaker { get; set; }
        public double? ICusCreLine { get; set; }
        public double? IArmoney { get; set; }
        public bool BFirst { get; set; }
        public int? Sbvid { get; set; }
        public string CDefine3 { get; set; }
        public DateTime? CDefine4 { get; set; }
        public int? CDefine5 { get; set; }
        public DateTime? CDefine6 { get; set; }
        public double? CDefine7 { get; set; }
        public string CDefine8 { get; set; }
        public string CDefine9 { get; set; }
        public string CDefine10 { get; set; }
        public string CDefine11 { get; set; }
        public string CDefine12 { get; set; }
        public string CDefine13 { get; set; }
        public string CDefine14 { get; set; }
        public int? CDefine15 { get; set; }
        public double? CDefine16 { get; set; }
        public string Cmodifier { get; set; }
        public string Dmoddate { get; set; }
        public string Dverifydate { get; set; }
        public short? ISale { get; set; }
        public string CCusName { get; set; }
        public string Clastcusname { get; set; }
        public string CCusPostCode { get; set; }
        public string Clastcustname { get; set; }
        public string Ccusperson { get; set; }
        public string Ccuspersoncode { get; set; }
        public string CCusDefine1 { get; set; }
        public string CCusDefine2 { get; set; }
        public string CBookType { get; set; }
        public string CBookDepcode { get; set; }
        public string CCusDefine3 { get; set; }
        public string CCusDefine4 { get; set; }
        public string CCusDefine5 { get; set; }
        public string CCusDefine6 { get; set; }
        public string CCusDefine7 { get; set; }
        public string CCusDefine8 { get; set; }
        public string CCusDefine9 { get; set; }
        public DateTime? DPinValidDate { get; set; }
        public string CCusDefine10 { get; set; }
        public int? CCusDefine11 { get; set; }
        public int? CCusDefine12 { get; set; }
        public double? CCusDefine13 { get; set; }
        public double? CCusDefine14 { get; set; }
        public DateTime? CCusDefine15 { get; set; }
        public DateTime? CCusDefine16 { get; set; }
        public string Ccushand { get; set; }
        public string Ccusphone { get; set; }
        public string Cbcode { get; set; }
        public string CBname { get; set; }
        public string CBaccount { get; set; }
        public string CRdCode { get; set; }
        public string CCloser { get; set; }
        public string Cauthid { get; set; }
        public string CCusAddress { get; set; }
        public bool Brequestsign { get; set; }
        public string CAddCode { get; set; }
        public string CDeliverUnit { get; set; }
        public string Csvouchtype { get; set; }
        public string CSourceCode { get; set; }
        public string CPsnOphone { get; set; }
        public string CPsnMobilePhone { get; set; }
        public string Ccontactname { get; set; }
        public string Cmobilephone { get; set; }
        public string COfficePhone { get; set; }
        public int Iflowid { get; set; }
        public string Cflowname { get; set; }
        public string Signvtid { get; set; }
        public bool Billafterlosssettle { get; set; }
        public int Bcusinvlimited { get; set; }
        public string Cgatheringplan { get; set; }
        public string Cgatheringplanname { get; set; }
        public DateTime? DCreditStart { get; set; }
        public int? Icreditdays { get; set; }
        public DateTime? DGatheringDate { get; set; }
        public bool Bbillbluesalelist { get; set; }
        public bool Bbillredsalelist { get; set; }
        public string Bcredit { get; set; }
        public bool Bcreditdate { get; set; }
        public int Bmustbook { get; set; }
        public string Ccreditcuscode { get; set; }
        public string Ccreditcusname { get; set; }
        public int Ioutgolden { get; set; }
        public int? Iverifystate { get; set; }
        public byte? Ireturncount { get; set; }
        public string Icreditstate { get; set; }
        public byte? Iswfcontrolled { get; set; }
        public DateTime? Dcreatesystime { get; set; }
        public DateTime? Dverifysystime { get; set; }
        public DateTime? Dmodifysystime { get; set; }
        public string CChanger { get; set; }
        public string CChangeMemo { get; set; }
        public int Bcashsale { get; set; }
        public string Cgathingcode { get; set; }
        public int Bsigncreate { get; set; }
        public int Bneedbill { get; set; }
        public int Iprintcount { get; set; }
        public string Csscode { get; set; }
        public string CSsname { get; set; }
        public string Cweighter { get; set; }
        public DateTime? Dweighttime { get; set; }
        public string CCusTradeCcode { get; set; }
        public string Ccustradecname { get; set; }
        public decimal? FEbweight { get; set; }
        public string CEbweightUnit { get; set; }
        public long? IEbexpressCoId { get; set; }
        public string CEbexpressCode { get; set; }
        public string CExpressCoName { get; set; }
        public string Cinvoicecompany { get; set; }
        public string Cinvoicecompanyabbname { get; set; }
        public int Baccswitchflag { get; set; }
        public DateTime? DEndDate { get; set; }
        public string CCccode { get; set; }
        public string CDccode { get; set; }
        public int? SeparateId { get; set; }
        public bool? Bcal { get; set; }
        public decimal? Zdsum { get; set; }
        public int? Linenum { get; set; }
        public byte Bnottogoldtax { get; set; }
        public string CEbtrnumber { get; set; }
        public string CEbbuyer { get; set; }
        public string CEbbuyerNote { get; set; }
        public string CEbprovince { get; set; }
        public string CEbcity { get; set; }
        public string CEbdistrict { get; set; }
        public string CInvoiceCusName { get; set; }
        public string CGcrouteCode { get; set; }
        public string Cgcroutename { get; set; }
    }
}
