using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class DispatchLists
    {
        public int AutoId { get; set; }
        public int Dlid { get; set; }
        public int? ICorId { get; set; }
        public string CWhCode { get; set; }
        public string CInvCode { get; set; }
        public decimal? IQuantity { get; set; }
        public decimal? INum { get; set; }
        public decimal? IQuotedPrice { get; set; }
        public decimal? IUnitPrice { get; set; }
        public decimal? ITaxUnitPrice { get; set; }
        public decimal? IMoney { get; set; }
        public decimal? ITax { get; set; }
        public decimal? ISum { get; set; }
        public decimal? IDisCount { get; set; }
        public decimal? INatUnitPrice { get; set; }
        public decimal? INatMoney { get; set; }
        public decimal? INatTax { get; set; }
        public decimal? INatSum { get; set; }
        public decimal? INatDisCount { get; set; }
        public decimal? ISettleNum { get; set; }
        public decimal? ISettleQuantity { get; set; }
        public int? IBatch { get; set; }
        public string CBatch { get; set; }
        public bool? BSettleAll { get; set; }
        public string CMemo { get; set; }
        public string CFree1 { get; set; }
        public string CFree2 { get; set; }
        public byte? ITb { get; set; }
        public DateTime? DvDate { get; set; }
        public decimal? Tbquantity { get; set; }
        public decimal? Tbnum { get; set; }
        public int? ISosId { get; set; }
        public int IDlsId { get; set; }
        public decimal? Kl { get; set; }
        public decimal? Kl2 { get; set; }
        public string CInvName { get; set; }
        public decimal? ITaxRate { get; set; }
        public string CDefine22 { get; set; }
        public string CDefine23 { get; set; }
        public string CDefine24 { get; set; }
        public string CDefine25 { get; set; }
        public double? CDefine26 { get; set; }
        public double? CDefine27 { get; set; }
        public decimal? FOutQuantity { get; set; }
        public decimal? FOutNum { get; set; }
        public string CItemCode { get; set; }
        public string CItemClass { get; set; }
        public decimal? FSaleCost { get; set; }
        public decimal? FSalePrice { get; set; }
        public string CVenAbbName { get; set; }
        public string CItemName { get; set; }
        public string CItemCname { get; set; }
        public string CFree3 { get; set; }
        public string CFree4 { get; set; }
        public string CFree5 { get; set; }
        public string CFree6 { get; set; }
        public string CFree7 { get; set; }
        public string CFree8 { get; set; }
        public string CFree9 { get; set; }
        public string CFree10 { get; set; }
        public bool? BIsStqc { get; set; }
        public decimal? IInvExchRate { get; set; }
        public string CUnitId { get; set; }
        public string CCode { get; set; }
        public decimal? IRetQuantity { get; set; }
        public decimal? FEnSettleQuan { get; set; }
        public decimal? FEnSettleSum { get; set; }
        public decimal? ISettlePrice { get; set; }
        public string CDefine28 { get; set; }
        public string CDefine29 { get; set; }
        public string CDefine30 { get; set; }
        public string CDefine31 { get; set; }
        public string CDefine32 { get; set; }
        public string CDefine33 { get; set; }
        public int? CDefine34 { get; set; }
        public int? CDefine35 { get; set; }
        public DateTime? CDefine36 { get; set; }
        public DateTime? CDefine37 { get; set; }
        public DateTime? DMdate { get; set; }
        public bool? BGsp { get; set; }
        public string CGspState { get; set; }
        public string CSoCode { get; set; }
        public string CCorCode { get; set; }
        public int? IPpartSeqId { get; set; }
        public int? IPpartId { get; set; }
        public decimal? IPpartQty { get; set; }
        public string CContractId { get; set; }
        public string CContractTagCode { get; set; }
        public Guid? CContractRowGuid { get; set; }
        public int? IMassDate { get; set; }
        public short? CMassUnit { get; set; }
        public bool? BQaneedCheck { get; set; }
        public bool? BQaurgency { get; set; }
        public bool? BQachecking { get; set; }
        public bool? BQachecked { get; set; }
        public decimal? IQaquantity { get; set; }
        public decimal? IQanum { get; set; }
        public string CCusInvCode { get; set; }
        public string CCusInvName { get; set; }
        public decimal? Fsumsignquantity { get; set; }
        public decimal? Fsumsignnum { get; set; }
        public string Cbaccounter { get; set; }
        public bool? Bcosting { get; set; }
        public string Cordercode { get; set; }
        public long? Iorderrowno { get; set; }
        public decimal? Fcusminprice { get; set; }
        public decimal? Icostquantity { get; set; }
        public decimal? Icostsum { get; set; }
        public byte? Ispecialtype { get; set; }
        public string Cvmivencode { get; set; }
        public decimal? Iexchsum { get; set; }
        public decimal? Imoneysum { get; set; }
        public long? Irowno { get; set; }
        public decimal? Frettbquantity { get; set; }
        public decimal? Fretsum { get; set; }
        public short? IExpiratDateCalcu { get; set; }
        public DateTime? DExpirationdate { get; set; }
        public string CExpirationdate { get; set; }
        public decimal? Cbatchproperty1 { get; set; }
        public decimal? Cbatchproperty2 { get; set; }
        public decimal? Cbatchproperty3 { get; set; }
        public decimal? Cbatchproperty4 { get; set; }
        public decimal? Cbatchproperty5 { get; set; }
        public string Cbatchproperty6 { get; set; }
        public string Cbatchproperty7 { get; set; }
        public string Cbatchproperty8 { get; set; }
        public string Cbatchproperty9 { get; set; }
        public DateTime? Cbatchproperty10 { get; set; }
        public decimal? DblPreExchMomey { get; set; }
        public decimal? DblPreMomey { get; set; }
        public short? Idemandtype { get; set; }
        public string Cdemandcode { get; set; }
        public string Cdemandmemo { get; set; }
        public string Cdemandid { get; set; }
        public long? Idemandseq { get; set; }
        public string Cvencode { get; set; }
        public string CReasonCode { get; set; }
        public string CInvSn { get; set; }
        public int? IInvSncount { get; set; }
        public bool? Bneedsign { get; set; }
        public bool? Bsignover { get; set; }
        public bool? Bneedloss { get; set; }
        public decimal? Flossrate { get; set; }
        public decimal? Frlossqty { get; set; }
        public decimal? Fulossqty { get; set; }
        public short? Isettletype { get; set; }
        public string Crelacuscode { get; set; }
        public string CLossMaker { get; set; }
        public DateTime? DLossDate { get; set; }
        public DateTime? DLossTime { get; set; }
        public long? Icoridlsid { get; set; }
        public decimal? Fretoutqty { get; set; }
        public string BodyOutid { get; set; }
        public decimal? FVeriBillQty { get; set; }
        public decimal? FVeriBillSum { get; set; }
        public decimal? FVeriRetQty { get; set; }
        public decimal? FVeriRetSum { get; set; }
        public decimal? FLastSettleQty { get; set; }
        public decimal? FLastSettleSum { get; set; }
        public string CBookWhcode { get; set; }
        public string CInVouchType { get; set; }
        public string CPosition { get; set; }
        public decimal? Fretqtywkp { get; set; }
        public decimal? Fretqtyykp { get; set; }
        public decimal? Frettbqtyykp { get; set; }
        public decimal? Fretsumykp { get; set; }
        public DateTime? Dkeepdate { get; set; }
        public string CScloser { get; set; }
        public long? Isaleoutid { get; set; }
        public bool? Bsaleprice { get; set; }
        public bool? Bgift { get; set; }
        public bool? Bmpforderclosed { get; set; }
        public string CbSysBarCode { get; set; }
        public double? Fxjquantity { get; set; }
        public double? Fxjnum { get; set; }
        public bool? BIacreatebill { get; set; }
        public string CParentCode { get; set; }
        public string CChildCode { get; set; }
        public decimal? Fchildqty { get; set; }
        public decimal? Fchildrate { get; set; }
        public byte? ICalcType { get; set; }
        public decimal? Fappretwkpqty { get; set; }
        public decimal? Fappretwkpsum { get; set; }
        public decimal? Fappretykpqty { get; set; }
        public decimal? Fappretykpsum { get; set; }
        public decimal? Fappretwkptbqty { get; set; }
        public decimal? Fappretykptbqty { get; set; }
        public long? Irtnappid { get; set; }
        public string Crtnappcode { get; set; }
        public decimal? Fretailrealamount { get; set; }
        public decimal? Fretailsettleamount { get; set; }
        public string CFactoryCode { get; set; }
        public int? GcsourceId { get; set; }
        public int? GcsourceIds { get; set; }
        public string CConfirmer { get; set; }
        public DateTime? DConfirmDate { get; set; }
    }
}
