using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class Inventory
    {
        public string CInvCode { get; set; }
        public string CInvAddCode { get; set; }
        public string CInvName { get; set; }
        public string CInvStd { get; set; }
        public string CInvCcode { get; set; }
        public string CVenCode { get; set; }
        public string CReplaceItem { get; set; }
        public string CPosition { get; set; }
        public bool? BSale { get; set; }
        public bool? BPurchase { get; set; }
        public bool? BSelf { get; set; }
        public bool? BComsume { get; set; }
        public bool? BProducing { get; set; }
        public bool? BService { get; set; }
        public bool? BAccessary { get; set; }
        public double? ITaxRate { get; set; }
        public double? IInvWeight { get; set; }
        public double? IVolume { get; set; }
        public double? IInvRcost { get; set; }
        public double? IInvSprice { get; set; }
        public double? IInvScost { get; set; }
        public double? IInvLscost { get; set; }
        public double? IInvNcost { get; set; }
        public double? IInvAdvance { get; set; }
        public double? IInvBatch { get; set; }
        public double? ISafeNum { get; set; }
        public double? ITopSum { get; set; }
        public double? ILowSum { get; set; }
        public double? IOverStock { get; set; }
        public string CInvAbc { get; set; }
        public bool? BInvQuality { get; set; }
        public bool? BInvBatch { get; set; }
        public bool? BInvEntrust { get; set; }
        public bool? BInvOverStock { get; set; }
        public DateTime? DSdate { get; set; }
        public DateTime? DEdate { get; set; }
        public bool? BFree1 { get; set; }
        public bool? BFree2 { get; set; }
        public string CInvDefine1 { get; set; }
        public string CInvDefine2 { get; set; }
        public string CInvDefine3 { get; set; }
        public int IId { get; set; }
        public bool? BInvType { get; set; }
        public double? IInvMpcost { get; set; }
        public string CQuality { get; set; }
        public double? IInvSaleCost { get; set; }
        public double? IInvScost1 { get; set; }
        public double? IInvScost2 { get; set; }
        public double? IInvScost3 { get; set; }
        public bool? BFree3 { get; set; }
        public bool? BFree4 { get; set; }
        public bool? BFree5 { get; set; }
        public bool? BFree6 { get; set; }
        public bool? BFree7 { get; set; }
        public bool? BFree8 { get; set; }
        public bool? BFree9 { get; set; }
        public bool? BFree10 { get; set; }
        public string CCreatePerson { get; set; }
        public string CModifyPerson { get; set; }
        public DateTime? DModifyDate { get; set; }
        public double? FSubscribePoint { get; set; }
        public double? FVagQuantity { get; set; }
        public string CValueType { get; set; }
        public bool? BFixExch { get; set; }
        public double? FOutExcess { get; set; }
        public double? FInExcess { get; set; }
        public short? IMassDate { get; set; }
        public short? IWarnDays { get; set; }
        public double? FExpensesExch { get; set; }
        public bool? BTrack { get; set; }
        public bool? BSerial { get; set; }
        public bool? BBarCode { get; set; }
        public int? IId1 { get; set; }
        public string CBarCode { get; set; }
        public string CInvDefine4 { get; set; }
        public string CInvDefine5 { get; set; }
        public string CInvDefine6 { get; set; }
        public string CInvDefine7 { get; set; }
        public string CInvDefine8 { get; set; }
        public string CInvDefine9 { get; set; }
        public string CInvDefine10 { get; set; }
        public int? CInvDefine11 { get; set; }
        public int? CInvDefine12 { get; set; }
        public double? CInvDefine13 { get; set; }
        public double? CInvDefine14 { get; set; }
        public DateTime? CInvDefine15 { get; set; }
        public DateTime? CInvDefine16 { get; set; }
        public byte IGroupType { get; set; }
        public string CGroupCode { get; set; }
        public string CComUnitCode { get; set; }
        public string CAssComUnitCode { get; set; }
        public string CSacomUnitCode { get; set; }
        public string CPucomUnitCode { get; set; }
        public string CStcomUnitCode { get; set; }
        public string CCacomUnitCode { get; set; }
        public string CFrequency { get; set; }
        public short? IFrequency { get; set; }
        public short? IDays { get; set; }
        public DateTime? DLastDate { get; set; }
        public double? IWastage { get; set; }
        public bool? BSolitude { get; set; }
        public string CEnterprise { get; set; }
        public string CAddress { get; set; }
        public string CFile { get; set; }
        public string CLabel { get; set; }
        public string CCheckOut { get; set; }
        public string CLicence { get; set; }
        public bool? BSpecialties { get; set; }
        public string CDefWareHouse { get; set; }
        public double? IHighPrice { get; set; }
        public double? IExpSaleRate { get; set; }
        public string CPriceGroup { get; set; }
        public string COfferGrade { get; set; }
        public double? IOfferRate { get; set; }
        public string CMonth { get; set; }
        public short? IAdvanceDate { get; set; }
        public string CCurrencyName { get; set; }
        public string CProduceAddress { get; set; }
        public string CProduceNation { get; set; }
        public string CRegisterNo { get; set; }
        public string CEnterNo { get; set; }
        public string CPackingType { get; set; }
        public string CEnglishName { get; set; }
        public bool? BPropertyCheck { get; set; }
        public string CPreparationType { get; set; }
        public string CCommodity { get; set; }
        public byte IRecipeBatch { get; set; }
        public string CNotPatentName { get; set; }
        public byte[] Pubufts { get; set; }
        public bool? BPromotSales { get; set; }
        public short? IPlanPolicy { get; set; }
        public short? IRopmethod { get; set; }
        public short? IBatchRule { get; set; }
        public double? FBatchIncrement { get; set; }
        public int? IAssureProvideDays { get; set; }
        public short? ITestStyle { get; set; }
        public short? IDtmethod { get; set; }
        public double? FDtrate { get; set; }
        public double? FDtnum { get; set; }
        public string CDtunit { get; set; }
        public short? IDtstyle { get; set; }
        public int? IQtmethod { get; set; }
        public Guid? PictureGuid { get; set; }
        public bool? BPlanInv { get; set; }
        public bool? BProxyForeign { get; set; }
        public bool? BAtomodel { get; set; }
        public bool? BCheckItem { get; set; }
        public bool? BPtomodel { get; set; }
        public bool? BEquipment { get; set; }
        public string CProductUnit { get; set; }
        public double? FOrderUpLimit { get; set; }
        public short? CMassUnit { get; set; }
        public double? FRetailPrice { get; set; }
        public string CInvDepCode { get; set; }
        public int? IAlterAdvance { get; set; }
        public double? FAlterBaseNum { get; set; }
        public string CPlanMethod { get; set; }
        public bool? BMps { get; set; }
        public bool? BRop { get; set; }
        public bool? BRePlan { get; set; }
        public string CSrpolicy { get; set; }
        public bool? BBillUnite { get; set; }
        public int? ISupplyDay { get; set; }
        public double? FSupplyMulti { get; set; }
        public double? FMinSupply { get; set; }
        public bool? BCutMantissa { get; set; }
        public string CInvPersonCode { get; set; }
        public int? IInvTfId { get; set; }
        public string CEngineerFigNo { get; set; }
        public bool? BInTotalCost { get; set; }
        public short ISupplyType { get; set; }
        public bool? BConfigFree1 { get; set; }
        public bool? BConfigFree2 { get; set; }
        public bool? BConfigFree3 { get; set; }
        public bool? BConfigFree4 { get; set; }
        public bool? BConfigFree5 { get; set; }
        public bool? BConfigFree6 { get; set; }
        public bool? BConfigFree7 { get; set; }
        public bool? BConfigFree8 { get; set; }
        public bool? BConfigFree9 { get; set; }
        public bool? BConfigFree10 { get; set; }
        public short? IDtlevel { get; set; }
        public string CDtaql { get; set; }
        public bool? BPeriodDt { get; set; }
        public string CDtperiod { get; set; }
        public int? IBigMonth { get; set; }
        public int? IBigDay { get; set; }
        public int? ISmallMonth { get; set; }
        public int? ISmallDay { get; set; }
        public bool? BOutInvDt { get; set; }
        public bool? BBackInvDt { get; set; }
        public short? IEndDtstyle { get; set; }
        public bool? BDtwarnInv { get; set; }
        public double? FBackTaxRate { get; set; }
        public string CCiqcode { get; set; }
        public string CWgroupCode { get; set; }
        public string CWunit { get; set; }
        public double? FGrossW { get; set; }
        public string CVgroupCode { get; set; }
        public string CVunit { get; set; }
        public double? FLength { get; set; }
        public double? FWidth { get; set; }
        public double? FHeight { get; set; }
        public int? IDtucounter { get; set; }
        public int? IDtdcounter { get; set; }
        public int? IBatchCounter { get; set; }
        public string CShopUnit { get; set; }
        public string CPurPersonCode { get; set; }
        public bool? BImportMedicine { get; set; }
        public bool? BFirstBusiMedicine { get; set; }
        public bool? BForeExpland { get; set; }
        public string CInvPlanCode { get; set; }
        public double FConvertRate { get; set; }
        public DateTime? DReplaceDate { get; set; }
        public bool? BInvModel { get; set; }
        public bool? BKccutMantissa { get; set; }
        public bool? BReceiptByDt { get; set; }
        public double? IImpTaxRate { get; set; }
        public double? IExpTaxRate { get; set; }
        public bool? BExpSale { get; set; }
        public double? IDrawBatch { get; set; }
        public bool? BCheckBsatp { get; set; }
        public string CInvProjectCode { get; set; }
        public short? ITestRule { get; set; }
        public string CRuleCode { get; set; }
        public bool? BCheckFree1 { get; set; }
        public bool? BCheckFree2 { get; set; }
        public bool? BCheckFree3 { get; set; }
        public bool? BCheckFree4 { get; set; }
        public bool? BCheckFree5 { get; set; }
        public bool? BCheckFree6 { get; set; }
        public bool? BCheckFree7 { get; set; }
        public bool? BCheckFree8 { get; set; }
        public bool? BCheckFree9 { get; set; }
        public bool? BCheckFree10 { get; set; }
        public bool? BBomMain { get; set; }
        public bool? BBomSub { get; set; }
        public bool? BProductBill { get; set; }
        public short ICheckAtp { get; set; }
        public int? IInvAtpid { get; set; }
        public int? IPlanTfDay { get; set; }
        public int? IOverlapDay { get; set; }
        public bool? BPiece { get; set; }
        public bool? BSrvItem { get; set; }
        public bool? BSrvFittings { get; set; }
        public double? FMaxSupply { get; set; }
        public double? FMinSplit { get; set; }
        public bool? BSpecialOrder { get; set; }
        public bool? BTrackSaleBill { get; set; }
        public string CInvMnemCode { get; set; }
        public short? IPlanDefault { get; set; }
        public double? IPfbatchQty { get; set; }
        public int? IAllocatePrintDgt { get; set; }
        public bool? BCheckBatch { get; set; }
        public bool? BMngOldpart { get; set; }
        public short? IOldpartMngRule { get; set; }
        public string CRetailDefReturnWh { get; set; }
    }
}
