using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class PoPodetails
    {
        public int Id { get; set; }
        public string CPoid { get; set; }
        public string CInvCode { get; set; }
        public decimal? IQuantity { get; set; }
        public decimal? INum { get; set; }
        public decimal? IQuotedPrice { get; set; }
        public decimal? IUnitPrice { get; set; }
        public decimal? IMoney { get; set; }
        public decimal? ITax { get; set; }
        public decimal? ISum { get; set; }
        public decimal? IDisCount { get; set; }
        public decimal? INatUnitPrice { get; set; }
        public decimal? INatMoney { get; set; }
        public decimal? INatTax { get; set; }
        public decimal? INatSum { get; set; }
        public decimal? INatDisCount { get; set; }
        public DateTime? DArriveDate { get; set; }
        public decimal? IReceivedQty { get; set; }
        public decimal? IReceivedNum { get; set; }
        public decimal? IReceivedMoney { get; set; }
        public decimal? IInvQty { get; set; }
        public decimal? IInvNum { get; set; }
        public decimal? IInvMoney { get; set; }
        public string CFree1 { get; set; }
        public string CFree2 { get; set; }
        public decimal? INatInvMoney { get; set; }
        public decimal? IOriTotal { get; set; }
        public decimal? ITotal { get; set; }
        public decimal? IPerTaxRate { get; set; }
        public string CDefine22 { get; set; }
        public string CDefine23 { get; set; }
        public string CDefine24 { get; set; }
        public string CDefine25 { get; set; }
        public double? CDefine26 { get; set; }
        public double? CDefine27 { get; set; }
        public byte? Iflag { get; set; }
        public string CItemCode { get; set; }
        public string CItemClass { get; set; }
        public int? Ppcids { get; set; }
        public string CItemName { get; set; }
        public string CFree3 { get; set; }
        public string CFree4 { get; set; }
        public string CFree5 { get; set; }
        public string CFree6 { get; set; }
        public string CFree7 { get; set; }
        public string CFree8 { get; set; }
        public string CFree9 { get; set; }
        public string CFree10 { get; set; }
        public byte? BGsp { get; set; }
        public int? Poid { get; set; }
        public string CUnitId { get; set; }
        public decimal? ITaxPrice { get; set; }
        public decimal? IArrQty { get; set; }
        public decimal? IArrNum { get; set; }
        public decimal? IArrMoney { get; set; }
        public decimal? INatArrMoney { get; set; }
        public int? IAppIds { get; set; }
        public string CDefine28 { get; set; }
        public string CDefine29 { get; set; }
        public string CDefine30 { get; set; }
        public string CDefine31 { get; set; }
        public string CDefine32 { get; set; }
        public string CDefine33 { get; set; }
        public int? CDefine34 { get; set; }
        public int? CDefine35 { get; set; }
        public DateTime? CDefine36 { get; set; }
        public DateTime? CDefine37 { get; set; }
        public int? ISosId { get; set; }
        public bool? BTaxCost { get; set; }
        public string CSource { get; set; }
        public string CbCloser { get; set; }
        public int? IPpartId { get; set; }
        public decimal? IPquantity { get; set; }
        public int? IPtoseq { get; set; }
        public byte? SoType { get; set; }
        public string SoDid { get; set; }
        public Guid? ContractRowGuid { get; set; }
        public string Cupsocode { get; set; }
        public decimal? IInvMpcost { get; set; }
        public string ContractCode { get; set; }
        public string ContractRowNo { get; set; }
        public decimal? FPoValidQuantity { get; set; }
        public decimal? FPoValidNum { get; set; }
        public decimal? FPoArrQuantity { get; set; }
        public decimal? FPoArrNum { get; set; }
        public decimal? FPoRetQuantity { get; set; }
        public decimal? FPoRetNum { get; set; }
        public decimal? FPoRefuseQuantity { get; set; }
        public decimal? FPoRefuseNum { get; set; }
        public byte[] DUfts { get; set; }
        public int? Iorderdid { get; set; }
        public byte? Iordertype { get; set; }
        public string Csoordercode { get; set; }
        public int? Iorderseq { get; set; }
        public DateTime? CbCloseTime { get; set; }
        public DateTime? CbCloseDate { get; set; }
        public string CBgItemCode { get; set; }
        public string CBgItemName { get; set; }
        public string CBgCaliberKey1 { get; set; }
        public string CBgCaliberKeyName1 { get; set; }
        public string CBgCaliberKey2 { get; set; }
        public string CBgCaliberKeyName2 { get; set; }
        public string CBgCaliberKey3 { get; set; }
        public string CBgCaliberKeyName3 { get; set; }
        public string CBgCaliberCode1 { get; set; }
        public string CBgCaliberName1 { get; set; }
        public string CBgCaliberCode2 { get; set; }
        public string CBgCaliberName2 { get; set; }
        public string CBgCaliberCode3 { get; set; }
        public string CBgCaliberName3 { get; set; }
        public byte? IBgCtrl { get; set; }
        public string CBgAuditopinion { get; set; }
        public decimal? Fexquantity { get; set; }
        public decimal? Fexnum { get; set; }
        public int? Ivouchrowno { get; set; }
        public string CBgCaliberKey4 { get; set; }
        public string CBgCaliberKeyName4 { get; set; }
        public string CBgCaliberKey5 { get; set; }
        public string CBgCaliberKeyName5 { get; set; }
        public string CBgCaliberKey6 { get; set; }
        public string CBgCaliberKeyName6 { get; set; }
        public string CBgCaliberCode4 { get; set; }
        public string CBgCaliberName4 { get; set; }
        public string CBgCaliberCode5 { get; set; }
        public string CBgCaliberName5 { get; set; }
        public string CBgCaliberCode6 { get; set; }
        public string CBgCaliberName6 { get; set; }
        public string Csocode { get; set; }
        public int? Irowno { get; set; }
        public decimal? Freceivedqty { get; set; }
        public decimal? Freceivednum { get; set; }
        public string Cxjspdids { get; set; }
        public string CbMemo { get; set; }
        public string Cbsysbarcode { get; set; }
        public string Planlotnumber { get; set; }
        public short? Bgift { get; set; }
        public string CFactoryCode { get; set; }
        public int? GcsourceId { get; set; }
        public int? GcsourceIds { get; set; }
        public string GcupCardNum { get; set; }
        public int? GcupId { get; set; }
        public int? GcupIds { get; set; }
        public string YycInvname { get; set; }
        public string Clsbwhcode { get; set; }
        public string Csyssourceautoid { get; set; }
    }
}
