using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class PuArrivalVouchs
    {
        public int Autoid { get; set; }
        public int? Id { get; set; }
        public string CWhCode { get; set; }
        public string CInvCode { get; set; }
        public decimal? INum { get; set; }
        public decimal IQuantity { get; set; }
        public decimal? IOriCost { get; set; }
        public decimal? IOriTaxCost { get; set; }
        public decimal? IOriMoney { get; set; }
        public decimal? IOriTaxPrice { get; set; }
        public decimal? IOriSum { get; set; }
        public decimal? ICost { get; set; }
        public decimal? IMoney { get; set; }
        public decimal? ITaxPrice { get; set; }
        public decimal? ISum { get; set; }
        public string CFree1 { get; set; }
        public string CFree2 { get; set; }
        public string CFree3 { get; set; }
        public string CFree4 { get; set; }
        public string CFree5 { get; set; }
        public string CFree6 { get; set; }
        public string CFree7 { get; set; }
        public string CFree8 { get; set; }
        public string CFree9 { get; set; }
        public string CFree10 { get; set; }
        public decimal ITaxRate { get; set; }
        public string CDefine22 { get; set; }
        public string CDefine23 { get; set; }
        public string CDefine24 { get; set; }
        public string CDefine25 { get; set; }
        public double? CDefine26 { get; set; }
        public double? CDefine27 { get; set; }
        public string CDefine28 { get; set; }
        public string CDefine29 { get; set; }
        public string CDefine30 { get; set; }
        public string CDefine31 { get; set; }
        public string CDefine32 { get; set; }
        public string CDefine33 { get; set; }
        public int? CDefine34 { get; set; }
        public int? CDefine35 { get; set; }
        public DateTime? CDefine36 { get; set; }
        public DateTime? CDefine37 { get; set; }
        public string CItemClass { get; set; }
        public string CItemCode { get; set; }
        public int? IPosId { get; set; }
        public string CItemName { get; set; }
        public string CUnitId { get; set; }
        public decimal? FValidInQuan { get; set; }
        public decimal? FKpquantity { get; set; }
        public decimal? FRealQuantity { get; set; }
        public decimal? FValidQuantity { get; set; }
        public decimal? FinValidQuantity { get; set; }
        public string CCloser { get; set; }
        public int? ICorId { get; set; }
        public decimal? FRetQuantity { get; set; }
        public decimal? FInValidInQuan { get; set; }
        public byte? BGsp { get; set; }
        public string CBatch { get; set; }
        public DateTime? DVdate { get; set; }
        public DateTime? DPdate { get; set; }
        public decimal? FRefuseQuantity { get; set; }
        public string CGspState { get; set; }
        public decimal? FValidNum { get; set; }
        public decimal? FValidInNum { get; set; }
        public decimal? FInValidNum { get; set; }
        public decimal? FRealNum { get; set; }
        public bool? BTaxCost { get; set; }
        public byte? BInspect { get; set; }
        public decimal? FRefuseNum { get; set; }
        public int? IPpartId { get; set; }
        public decimal? IPquantity { get; set; }
        public int? IPtoseq { get; set; }
        public string SoDid { get; set; }
        public byte? SoType { get; set; }
        public Guid? ContractRowGuid { get; set; }
        public int? Imassdate { get; set; }
        public byte? Cmassunit { get; set; }
        public byte? Bexigency { get; set; }
        public string Cbcloser { get; set; }
        public decimal? FSumRefuseQuantity { get; set; }
        public decimal? FsumRefuseNum { get; set; }
        public decimal? FRetNum { get; set; }
        public decimal? FDtquantity { get; set; }
        public decimal? FInvalidInNum { get; set; }
        public decimal? FDegradeQuantity { get; set; }
        public decimal? FDegradeNum { get; set; }
        public decimal? FDegradeInQuantity { get; set; }
        public decimal? FDegradeInNum { get; set; }
        public decimal? FInspectQuantity { get; set; }
        public decimal? FInspectNum { get; set; }
        public decimal? IInvMpcost { get; set; }
        public string Guids { get; set; }
        public decimal? Iinvexchrate { get; set; }
        public string ObjectidSource { get; set; }
        public int? AutoidSource { get; set; }
        public string UftsSource { get; set; }
        public int? IrownoSource { get; set; }
        public string Csocode { get; set; }
        public int? Isorowno { get; set; }
        public int? Iorderid { get; set; }
        public string Cordercode { get; set; }
        public int? Iorderrowno { get; set; }
        public DateTime? Dlineclosedate { get; set; }
        public string ContractCode { get; set; }
        public string ContractRowNo { get; set; }
        public bool? RejectSource { get; set; }
        public int? Iciqbookid { get; set; }
        public string Cciqbookcode { get; set; }
        public string Cciqcode { get; set; }
        public decimal? Fciqchangrate { get; set; }
        public int? Irejectautoid { get; set; }
        public short? IExpiratDateCalcu { get; set; }
        public string CExpirationdate { get; set; }
        public DateTime? DExpirationdate { get; set; }
        public string Cupsocode { get; set; }
        public int? Iorderdid { get; set; }
        public byte? Iordertype { get; set; }
        public string Csoordercode { get; set; }
        public int? Iorderseq { get; set; }
        public decimal? CBatchProperty1 { get; set; }
        public decimal? CBatchProperty2 { get; set; }
        public decimal? CBatchProperty3 { get; set; }
        public decimal? CBatchProperty4 { get; set; }
        public decimal? CBatchProperty5 { get; set; }
        public string CBatchProperty6 { get; set; }
        public string CBatchProperty7 { get; set; }
        public string CBatchProperty8 { get; set; }
        public string CBatchProperty9 { get; set; }
        public DateTime? CBatchProperty10 { get; set; }
        public int? Ivouchrowno { get; set; }
        public int? Irowno { get; set; }
        public string CbMemo { get; set; }
        public string Cbsysbarcode { get; set; }
        public string Carrivalcode { get; set; }
        public double? Ipickedquantity { get; set; }
        public double? Ipickednum { get; set; }
        public string ISourceMocode { get; set; }
        public int? ISourceModetailsId { get; set; }
        public decimal? Freworkquantity { get; set; }
        public decimal? Freworknum { get; set; }
        public decimal? Fsumreworkquantity { get; set; }
        public decimal? Fsumreworknum { get; set; }
        public byte? IProductType { get; set; }
        public string CMainInvCode { get; set; }
        public int? IMainMoDetailsId { get; set; }
        public string PlanLotNumber { get; set; }
        public short? Bgift { get; set; }
        public string CFactoryCode { get; set; }
    }
}
