using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class Rdrecords11
    {
        public long AutoId { get; set; }
        public long Id { get; set; }
        public string CInvCode { get; set; }
        public decimal? INum { get; set; }
        public decimal? IQuantity { get; set; }
        public decimal? IUnitCost { get; set; }
        public decimal? IPrice { get; set; }
        public decimal? IAprice { get; set; }
        public decimal? IPunitCost { get; set; }
        public decimal? IPprice { get; set; }
        public string CBatch { get; set; }
        public string CObjCode { get; set; }
        public long? CVouchCode { get; set; }
        public string CInVouchCode { get; set; }
        public string Cinvouchtype { get; set; }
        public decimal? ISoutQuantity { get; set; }
        public decimal? ISoutNum { get; set; }
        public long? Coutvouchid { get; set; }
        public string Coutvouchtype { get; set; }
        public decimal? ISredOutQuantity { get; set; }
        public decimal? ISredOutNum { get; set; }
        public string CFree1 { get; set; }
        public string CFree2 { get; set; }
        public byte IFlag { get; set; }
        public decimal? ISquantity { get; set; }
        public decimal? ISnum { get; set; }
        public decimal? IFnum { get; set; }
        public decimal? IFquantity { get; set; }
        public DateTime? DVdate { get; set; }
        public long? ITrIds { get; set; }
        public string CPosition { get; set; }
        public string CDefine22 { get; set; }
        public string CDefine23 { get; set; }
        public string CDefine24 { get; set; }
        public string CDefine25 { get; set; }
        public double? CDefine26 { get; set; }
        public double? CDefine27 { get; set; }
        public string CItemClass { get; set; }
        public string CItemCode { get; set; }
        public string CName { get; set; }
        public string CItemCname { get; set; }
        public string CFree3 { get; set; }
        public string CFree4 { get; set; }
        public string CFree5 { get; set; }
        public string CFree6 { get; set; }
        public string CFree7 { get; set; }
        public string CFree8 { get; set; }
        public string CFree9 { get; set; }
        public string CFree10 { get; set; }
        public string CBarCode { get; set; }
        public decimal? INquantity { get; set; }
        public decimal? INnum { get; set; }
        public string CAssUnit { get; set; }
        public DateTime? DMadeDate { get; set; }
        public int? IMassDate { get; set; }
        public string CDefine28 { get; set; }
        public string CDefine29 { get; set; }
        public string CDefine30 { get; set; }
        public string CDefine31 { get; set; }
        public string CDefine32 { get; set; }
        public string CDefine33 { get; set; }
        public int? CDefine34 { get; set; }
        public int? CDefine35 { get; set; }
        public DateTime? CDefine36 { get; set; }
        public DateTime? CDefine37 { get; set; }
        public long? IMpoIds { get; set; }
        public long? ICheckIds { get; set; }
        public string CBvencode { get; set; }
        public bool? BGsp { get; set; }
        public string CGspState { get; set; }
        public string CCheckCode { get; set; }
        public long? ICheckIdBaks { get; set; }
        public string CRejectCode { get; set; }
        public long? IRejectIds { get; set; }
        public string CCheckPersonCode { get; set; }
        public DateTime? DCheckDate { get; set; }
        public short? CMassUnit { get; set; }
        public string CMoLotCode { get; set; }
        public decimal? IMaterialFee { get; set; }
        public decimal? IProcessCost { get; set; }
        public decimal? IProcessFee { get; set; }
        public DateTime? DMsdate { get; set; }
        public decimal? ISmaterialFee { get; set; }
        public decimal? ISprocessFee { get; set; }
        public int? IOmoDid { get; set; }
        public long? BFilled { get; set; }
        public bool? BChecked { get; set; }
        public long? IOmoMid { get; set; }
        public string Cmworkcentercode { get; set; }
        public bool? BLpuseFree { get; set; }
        public int? IRsrowNo { get; set; }
        public long? IOriTrackId { get; set; }
        public string Coritracktype { get; set; }
        public string Cbaccounter { get; set; }
        public DateTime? DbKeepDate { get; set; }
        public bool? BCosting { get; set; }
        public bool? BVmiused { get; set; }
        public decimal? IVmisettleQuantity { get; set; }
        public decimal? IVmisettleNum { get; set; }
        public string Cvmivencode { get; set; }
        public int? IInvSncount { get; set; }
        public string Cwhpersoncode { get; set; }
        public string Cwhpersonname { get; set; }
        public long? IMaIds { get; set; }
        public string Cserviceoid { get; set; }
        public string Cbserviceoid { get; set; }
        public decimal? Iinvexchrate { get; set; }
        public string Corufts { get; set; }
        public string Comcode { get; set; }
        public string Cmocode { get; set; }
        public string Invcode { get; set; }
        public int? Imoseq { get; set; }
        public string Iopseq { get; set; }
        public string Copdesc { get; set; }
        public Guid? StrContractGuid { get; set; }
        public short? IExpiratDateCalcu { get; set; }
        public string CExpirationdate { get; set; }
        public DateTime? DExpirationdate { get; set; }
        public string Cciqbookcode { get; set; }
        public decimal? IBondedSumQty { get; set; }
        public int? Productinids { get; set; }
        public int? Iorderdid { get; set; }
        public byte? Iordertype { get; set; }
        public string Iordercode { get; set; }
        public int? Iorderseq { get; set; }
        public string Isodid { get; set; }
        public byte? Isotype { get; set; }
        public string Csocode { get; set; }
        public int? Isoseq { get; set; }
        public string Ipesodid { get; set; }
        public byte? Ipesotype { get; set; }
        public string Cpesocode { get; set; }
        public int? Ipesoseq { get; set; }
        public decimal? CBatchProperty1 { get; set; }
        public decimal? CBatchProperty2 { get; set; }
        public decimal? CBatchProperty3 { get; set; }
        public decimal? CBatchProperty4 { get; set; }
        public decimal? CBatchProperty5 { get; set; }
        public string CBatchProperty6 { get; set; }
        public string CBatchProperty7 { get; set; }
        public string CBatchProperty8 { get; set; }
        public string CBatchProperty9 { get; set; }
        public DateTime? CBatchProperty10 { get; set; }
        public string CbMemo { get; set; }
        public int? Applydid { get; set; }
        public string Applycode { get; set; }
        public int? Irowno { get; set; }
        public Guid? Strowguid { get; set; }
        public string Cservicecode { get; set; }
        public byte[] Rowufts { get; set; }
        public decimal? Ipreuseqty { get; set; }
        public decimal? Ipreuseinum { get; set; }
        public int? Bsupersede { get; set; }
        public decimal? Isupersedeqty { get; set; }
        public int? Isupersedempoids { get; set; }
        public Guid? Imoallocatesubid { get; set; }
        public int? CInVoucherLineId { get; set; }
        public string CInVoucherCode { get; set; }
        public string CInVoucherType { get; set; }
        public string Cbsysbarcode { get; set; }
        public string CSourceMocode { get; set; }
        public int? ISourceModetailsid { get; set; }
        public string Cplanlotcode { get; set; }
        public int? Bcanreplace { get; set; }
        public short? Iposflag { get; set; }
        public short? BOutMaterials { get; set; }
    }
}
