using System;
using System.Collections.Generic;

namespace MicroFeel.YongYou.Models.Models
{
    public partial class SoSodetails
    {
        public int AutoId { get; set; }
        public string CSocode { get; set; }
        public string CInvCode { get; set; }
        public DateTime? DPreDate { get; set; }
        public decimal? IQuantity { get; set; }
        public decimal? INum { get; set; }
        public decimal? IQuotedPrice { get; set; }
        public decimal? IUnitPrice { get; set; }
        public decimal? ITaxUnitPrice { get; set; }
        public decimal? IMoney { get; set; }
        public decimal? ITax { get; set; }
        public decimal? ISum { get; set; }
        public decimal? IDisCount { get; set; }
        public decimal? INatUnitPrice { get; set; }
        public decimal? INatMoney { get; set; }
        public decimal? INatTax { get; set; }
        public decimal? INatSum { get; set; }
        public decimal? INatDisCount { get; set; }
        public decimal? IFhnum { get; set; }
        public decimal? IFhquantity { get; set; }
        public decimal? IFhmoney { get; set; }
        public decimal? IKpquantity { get; set; }
        public decimal? IKpnum { get; set; }
        public decimal? IKpmoney { get; set; }
        public string CMemo { get; set; }
        public string CFree1 { get; set; }
        public string CFree2 { get; set; }
        public int? BFh { get; set; }
        public int ISosId { get; set; }
        public decimal? Kl { get; set; }
        public decimal? Kl2 { get; set; }
        public string CInvName { get; set; }
        public decimal? ITaxRate { get; set; }
        public string CDefine22 { get; set; }
        public string CDefine23 { get; set; }
        public string CDefine24 { get; set; }
        public string CDefine25 { get; set; }
        public double? CDefine26 { get; set; }
        public double? CDefine27 { get; set; }
        public string CItemCode { get; set; }
        public string CItemClass { get; set; }
        public string CItemName { get; set; }
        public string CItemCname { get; set; }
        public string CFree3 { get; set; }
        public string CFree4 { get; set; }
        public string CFree5 { get; set; }
        public string CFree6 { get; set; }
        public string CFree7 { get; set; }
        public string CFree8 { get; set; }
        public string CFree9 { get; set; }
        public string CFree10 { get; set; }
        public decimal? IInvExchRate { get; set; }
        public string CUnitId { get; set; }
        public int? Id { get; set; }
        public string CDefine28 { get; set; }
        public string CDefine29 { get; set; }
        public string CDefine30 { get; set; }
        public string CDefine31 { get; set; }
        public string CDefine32 { get; set; }
        public string CDefine33 { get; set; }
        public int? CDefine34 { get; set; }
        public int? CDefine35 { get; set; }
        public DateTime? CDefine36 { get; set; }
        public DateTime? CDefine37 { get; set; }
        public decimal? FpurQuan { get; set; }
        public decimal? FSaleCost { get; set; }
        public decimal? FSalePrice { get; set; }
        public string CQuoCode { get; set; }
        public int? IQuoId { get; set; }
        public string CScloser { get; set; }
        public DateTime? DPreMoDate { get; set; }
        public int? IRowNo { get; set; }
        public int? ICusBomId { get; set; }
        public decimal? IMoQuantity { get; set; }
        public string CContractId { get; set; }
        public string CContractTagCode { get; set; }
        public Guid? CContractRowGuid { get; set; }
        public int? IPpartSeqId { get; set; }
        public int? IPpartId { get; set; }
        public decimal? IPpartQty { get; set; }
        public string CCusInvCode { get; set; }
        public string CCusInvName { get; set; }
        public decimal? IPreKeepQuantity { get; set; }
        public decimal? IPreKeepNum { get; set; }
        public decimal? IPreKeepTotQuantity { get; set; }
        public decimal? IPreKeepTotNum { get; set; }
        public DateTime? Dreleasedate { get; set; }
        public decimal? Fcusminprice { get; set; }
        public decimal? Fimquantity { get; set; }
        public decimal? Fomquantity { get; set; }
        public bool? Ballpurchase { get; set; }
        public decimal? Finquantity { get; set; }
        public decimal? Icostquantity { get; set; }
        public decimal? Icostsum { get; set; }
        public decimal? Foutquantity { get; set; }
        public decimal? Foutnum { get; set; }
        public decimal? Iexchsum { get; set; }
        public decimal? Imoneysum { get; set; }
        public byte[] Dufts { get; set; }
        public int? Iaoids { get; set; }
        public string Cpreordercode { get; set; }
        public decimal? Fretquantity { get; set; }
        public decimal? Fretnum { get; set; }
        public DateTime? Dbclosedate { get; set; }
        public DateTime? Dbclosesystime { get; set; }
        public bool? BOrderBom { get; set; }
        public byte? BOrderBomover { get; set; }
        public short? Idemandtype { get; set; }
        public string Cdemandcode { get; set; }
        public string Cdemandmemo { get; set; }
        public decimal? FPurSum { get; set; }
        public decimal? FPurBillQty { get; set; }
        public decimal? FPurBillSum { get; set; }
        public long? Iimid { get; set; }
        public string Ccorvouchtype { get; set; }
        public int? Icorrowno { get; set; }
        public bool? Busecusbom { get; set; }
        public Guid? BodyOutid { get; set; }
        public decimal? FVeriDispQty { get; set; }
        public decimal? FVeriDispSum { get; set; }
        public bool? Bsaleprice { get; set; }
        public bool? Bgift { get; set; }
        public int? Forecastdid { get; set; }
        public string Cdetailsdemandcode { get; set; }
        public string Cdetailsdemandmemo { get; set; }
        public decimal? FTransedQty { get; set; }
        public string CbSysBarCode { get; set; }
        public decimal? Fappqty { get; set; }
        public string CParentCode { get; set; }
        public string CChildCode { get; set; }
        public decimal? Fchildqty { get; set; }
        public decimal? Fchildrate { get; set; }
        public byte? ICalcType { get; set; }
        public long? ICurPartid { get; set; }
        public string CFactoryCode { get; set; }
        public int? GcsourceId { get; set; }
        public int? GcsourceIds { get; set; }
    }
}
